baseURL = "https://blog.monsterxx03.com"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Shining Moon"
theme = "zozo"
hasCJKLanguage = true
summaryLength = 200
paginate = 10
copyright = "monsterxx03"
enableRobotsTXT = true # generate robots.txt
enableEmoji = true
googleAnalytics = "UA-98667627-1"
disqusShortname = "mx03"

publishDir="docs"

[author]
    name = "monsterxx03"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Archive"
    url = "/posts/"
    weight = 20
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 40

[params]
    subtitle = "百种弊病,皆从懒生"
    enableMathJax = true
    enableSummary = true

[social]
    github = "https://github.com/monsterxx03"

[permalinks]
page = "/:slug/"
posts = "/:year/:month/:day/:title/"
